app_name: <insert-app-name>
repo_url: "<insert-repo-url>"
branch: "main"
artifact_name: "<insert-app-name>.jar"

db_type: "<insert-dbtype>"
db_host: "localhost"
db_port: <insert-port>
db_name: "<insert-db-name>"

service_name: "<insert-service-name>" # best - same as app_name
app_port: <insert-port>
