app_name: bankapp
repo_url: "https://github.com/manasa-bhagwat/java-app.git"
branch: "main"
artifact_name: "bankapp.jar"

db_type: "mysql"
db_host: "localhost"
db_port: 3306
db_name: "bankappdb"

service_name: "bankapp"
app_port: 8080
